version: '3.8'

services:
  front:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    # command: 'yarn dev'
    command: 'yarn start'
    ports:
      - '3000:3000'
